# Generated by Django 5.1.6 on 2025-03-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BWFapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="player",
            name="last_name",
            field=models.CharField(default=" ", max_length=100),
            preserve_default=False,
        ),
    ]
