# Generated by Django 5.1.6 on 2025-03-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BWFapp", "0002_rename_name_player_first_name_player_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="FemaleSinglePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("rank", models.IntegerField()),
                ("country", models.CharField(max_length=100)),
                ("nb_tournaments", models.IntegerField()),
                ("points", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="MaleSinglePlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("rank", models.IntegerField()),
                ("country", models.CharField(max_length=100)),
                ("nb_tournaments", models.IntegerField()),
                ("points", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Player",
        ),
    ]
