# Generated by Django 5.1.6 on 2025-03-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BWFapp", "0003_femalesingleplayer_malesingleplayer_delete_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="femalesingleplayer",
            name="country_image",
            field=models.ImageField(default="", upload_to="country_images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="malesingleplayer",
            name="country_image",
            field=models.ImageField(default="", upload_to="country_images/"),
            preserve_default=False,
        ),
    ]
