# Generated by Django 5.1.6 on 2025-03-11 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BWFapp", "0005_femalesingleplayer_date_malesingleplayer_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="femalesingleplayer",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name="malesingleplayer",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
