# Generated by Django 5.1.6 on 2025-03-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BWFapp", "0006_alter_femalesingleplayer_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="femalesingleplayer",
            name="id",
        ),
        migrations.RemoveField(
            model_name="malesingleplayer",
            name="id",
        ),
        migrations.AlterField(
            model_name="femalesingleplayer",
            name="rank",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="malesingleplayer",
            name="rank",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
